### ISSUE TITLE
Dynamic loading not supported

### ISSUE THREAD

**Issue by Martin2877** [kluctl/go-embed-python#12] opened 2023-02-27 09:25 UTC
I installed python module named "grpcio", but I failed when I run it with `go run .`

```
 File "/tmp/go-embedded-test-c2129af10b3925a5/test.py", line 5, in <module>
    from btab import BTAB, Engines, Search
  File "/tmp/go-embedded-test-c2129af10b3925a5/btab.py", line 1, in <module>
    import grpc
  File "/tmp/go-embedded-test-3c13bd27479a0448/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/tmp/go-embedded-test-3c13bd27479a0448/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: Dynamic loading not supported
```

**Comment by codablock** [comment] 2023-02-27 09:27
Hello, yes, dynamic loading is not supported right now as it does not work on musl based distros, which I rely heavily on due to the use of Alpine in all my docker images.

**Comment by codablock** [comment] 2023-04-11 07:29
This is basically the same as #17. The underlying issue here is the use of the Python MUSL build which does not support dynamic loading. Closing this as a duplicate of #17.

**Closed as completed by codablock** 2023-04-11 07:29 UTC
